# Generated by Django 3.0.4 on 2020-03-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_of_issue', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[[1, 'механическая коробка передач'], [2, 'автоматическая коробка передач'], [3, 'роботизированная коробка передач']])),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
