# Generated by Django 3.0.4 on 2020-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[[1, 'механическая коробка передач'], [2, 'автоматическая коробка передач'], [3, 'роботизированная коробка передач']], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_issue',
            field=models.IntegerField(null=True),
        ),
    ]
