# Generated by Django 3.0.4 on 2020-03-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200319_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colour',
        ),
    ]
